#############################################################################
# Makefile for building: VVG-cliente-1314-g03
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  VVG-cliente-1314-g03.pro
# Template: app
# Command: /home/katu/Qt5.2.0/5.2.0/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile VVG-cliente-1314-g03.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++ -I. -I. -I../Qt5.2.0/5.2.0/gcc_64/include -I../Qt5.2.0/5.2.0/gcc_64/include/QtMultimediaWidgets -I../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia -I../Qt5.2.0/5.2.0/gcc_64/include/QtWidgets -I../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork -I../Qt5.2.0/5.2.0/gcc_64/include/QtGui -I../Qt5.2.0/5.2.0/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/katu/Qt5.2.0/5.2.0/gcc_64 -Wl,-rpath,/home/katu/Qt5.2.0/5.2.0/gcc_64/lib -Wl,-rpath-link,/home/katu/Qt5.2.0/5.2.0/gcc_64/lib
LIBS          = $(SUBLIBS) -lopencv_core -lopencv_video -lopencv_imgproc -lprotobuf -L/home/katu/Qt5.2.0/5.2.0/gcc_64/lib -lQt5MultimediaWidgets -lQt5Multimedia -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/katu/Qt5.2.0/5.2.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mysignalhandler.cpp \
		cliente.cpp \
		capturebuffer.cpp \
		cvmatandqimage.cpp protocol.pb.cc \
		moc_mysignalhandler.cpp \
		moc_cliente.cpp \
		moc_capturebuffer.cpp
OBJECTS       = main.o \
		mysignalhandler.o \
		cliente.o \
		capturebuffer.o \
		cvmatandqimage.o \
		protocol.pb.o \
		moc_mysignalhandler.o \
		moc_cliente.o \
		moc_capturebuffer.o
DIST          = ../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/unix.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/linux.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-base.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/qconfig.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_config.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_post.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_pre.prf \
		opencv.pri \
		QtOpenCV.pri \
		protobuf.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_post.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qml_debug.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/declarative_debug.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/warn_on.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resources.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/moc.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/uic.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exceptions.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/yacc.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/lex.prf \
		VVG-cliente-1314-g03.pro \
		VVG-cliente-1314-g03.pro
QMAKE_TARGET  = VVG-cliente-1314-g03
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = VVG-cliente-1314-g03


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: VVG-cliente-1314-g03.pro ../Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf ../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/unix.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/linux.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-base.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/qconfig.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_config.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_post.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_pre.prf \
		opencv.pri \
		QtOpenCV.pri \
		protobuf.pri \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_post.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qml_debug.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/declarative_debug.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/warn_on.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resources.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/moc.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/uic.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exceptions.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/yacc.prf \
		../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/lex.prf \
		VVG-cliente-1314-g03.pro \
		/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5MultimediaWidgets.prl \
		/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Multimedia.prl \
		/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Gui.prl \
		/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Core.prl \
		/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Network.prl \
		/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Widgets.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile VVG-cliente-1314-g03.pro
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_pre.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/shell-unix.conf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/unix.conf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/linux.conf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base.conf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-base.conf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-unix.conf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/qconfig.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_functions.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_config.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_post.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_pre.prf:
opencv.pri:
QtOpenCV.pri:
protobuf.pri:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resolve_config.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_post.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qml_debug.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/declarative_debug.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/warn_on.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resources.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/moc.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/opengl.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/uic.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/thread.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exceptions.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/yacc.prf:
../Qt5.2.0/5.2.0/gcc_64/mkspecs/features/lex.prf:
VVG-cliente-1314-g03.pro:
/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5MultimediaWidgets.prl:
/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Multimedia.prl:
/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Gui.prl:
/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Core.prl:
/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Network.prl:
/home/katu/Qt5.2.0/5.2.0/gcc_64/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile VVG-cliente-1314-g03.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/VVG-cliente-1314-g031.0.0 || mkdir -p .tmp/VVG-cliente-1314-g031.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/VVG-cliente-1314-g031.0.0/ && $(COPY_FILE) --parents protocol.proto .tmp/VVG-cliente-1314-g031.0.0/ && $(COPY_FILE) --parents protocol.proto .tmp/VVG-cliente-1314-g031.0.0/ && $(COPY_FILE) --parents cvmatandqimage.h mysignalhandler.h cliente.h capturebuffer.h cvmatandqimage.h .tmp/VVG-cliente-1314-g031.0.0/ && $(COPY_FILE) --parents main.cpp mysignalhandler.cpp cliente.cpp capturebuffer.cpp cvmatandqimage.cpp .tmp/VVG-cliente-1314-g031.0.0/ && (cd `dirname .tmp/VVG-cliente-1314-g031.0.0` && $(TAR) VVG-cliente-1314-g031.0.0.tar VVG-cliente-1314-g031.0.0 && $(COMPRESS) VVG-cliente-1314-g031.0.0.tar) && $(MOVE) `dirname .tmp/VVG-cliente-1314-g031.0.0`/VVG-cliente-1314-g031.0.0.tar.gz . && $(DEL_FILE) -r .tmp/VVG-cliente-1314-g031.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_protobuf_decl_make_all: protocol.pb.h
compiler_protobuf_decl_clean:
	-$(DEL_FILE) protocol.pb.h
protocol.pb.h: protocol.proto
	protoc --cpp_out=. --proto_path=. --proto_path=../ protocol.proto

compiler_protobuf_impl_make_all: protocol.pb.cc
compiler_protobuf_impl_clean:
	-$(DEL_FILE) protocol.pb.cc
protocol.pb.cc: protocol.proto \
		protocol.pb.h
	


compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mysignalhandler.cpp moc_cliente.cpp moc_capturebuffer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mysignalhandler.cpp moc_cliente.cpp moc_capturebuffer.cpp
moc_mysignalhandler.cpp: ../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QSocketNotifier \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsocketnotifier.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qflags.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstring.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qchar.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QCoreApplication \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qeventloop.h \
		cliente.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QObject \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/QTcpSocket \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qhash.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpair.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvector.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qset.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QCamera \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamera.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsize.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrect.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediacontrol.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmultimedia.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaservice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraexposure.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaenumdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamerafocus.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraimageprocessing.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QMovie \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmovie.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimagereader.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qregion.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qline.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimageiohandler.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qplugin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonvalue.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfactoryinterface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTimer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTime \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatetime.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPixmap \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qcolor.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QBuffer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPainter \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainter.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtextoption.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpen.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qbrush.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfont.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontmetrics.h \
		cvmatandqimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QImage \
		capturebuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QDebug \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QAbstractVideoSurface \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideosurface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qvideoframe.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideobuffer.h \
		mysignalhandler.h
	/home/katu/Qt5.2.0/5.2.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) mysignalhandler.h -o moc_mysignalhandler.cpp

moc_cliente.cpp: ../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QObject \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qflags.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstring.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qchar.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/QTcpSocket \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qhash.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpair.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvector.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qset.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QCamera \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamera.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsize.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrect.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediacontrol.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmultimedia.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaservice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraexposure.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaenumdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamerafocus.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraimageprocessing.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QMovie \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmovie.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimagereader.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qregion.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qline.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimageiohandler.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qplugin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonvalue.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfactoryinterface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTimer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTime \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatetime.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPixmap \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qcolor.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QBuffer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPainter \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainter.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtextoption.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpen.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qbrush.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfont.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontmetrics.h \
		cvmatandqimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QImage \
		capturebuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QDebug \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QAbstractVideoSurface \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideosurface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qvideoframe.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideobuffer.h \
		cliente.h
	/home/katu/Qt5.2.0/5.2.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) cliente.h -o moc_cliente.cpp

moc_capturebuffer.cpp: ../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QDebug \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qflags.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qhash.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qchar.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpair.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstring.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvector.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qset.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QAbstractVideoSurface \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideosurface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qvideoframe.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrect.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsize.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qregion.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qline.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideobuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmultimedia.h \
		capturebuffer.h
	/home/katu/Qt5.2.0/5.2.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) capturebuffer.h -o moc_capturebuffer.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_protobuf_decl_clean compiler_protobuf_impl_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../Qt5.2.0/5.2.0/gcc_64/include/QtWidgets/QApplication \
		../Qt5.2.0/5.2.0/gcc_64/include/QtWidgets/qapplication.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qflags.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstring.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qchar.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qeventloop.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsize.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qcursor.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtWidgets/qwidget.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmargins.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrect.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpalette.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qcolor.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpair.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qbrush.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvector.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qregion.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qline.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qhash.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfont.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qset.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qurl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfile.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qguiapplication.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qinputmethod.h \
		mysignalhandler.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QSocketNotifier \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsocketnotifier.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QCoreApplication \
		cliente.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QObject \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/QTcpSocket \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QCamera \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamera.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediacontrol.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmultimedia.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaservice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraexposure.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaenumdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamerafocus.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraimageprocessing.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QMovie \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmovie.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimagereader.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimageiohandler.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qplugin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonvalue.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfactoryinterface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTimer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTime \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatetime.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPixmap \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QBuffer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPainter \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainter.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtextoption.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpen.h \
		cvmatandqimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QImage \
		capturebuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QDebug \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QAbstractVideoSurface \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideosurface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qvideoframe.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideobuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QSettings \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mysignalhandler.o: mysignalhandler.cpp mysignalhandler.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QSocketNotifier \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsocketnotifier.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qflags.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstring.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qchar.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QCoreApplication \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qeventloop.h \
		cliente.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QObject \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/QTcpSocket \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qhash.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpair.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvector.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qset.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QCamera \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamera.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsize.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrect.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediacontrol.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmultimedia.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaservice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraexposure.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaenumdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamerafocus.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraimageprocessing.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QMovie \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmovie.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimagereader.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qregion.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qline.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimageiohandler.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qplugin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonvalue.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfactoryinterface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTimer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTime \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatetime.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPixmap \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qcolor.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QBuffer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPainter \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainter.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtextoption.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpen.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qbrush.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfont.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontmetrics.h \
		cvmatandqimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QImage \
		capturebuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QDebug \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QAbstractVideoSurface \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideosurface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qvideoframe.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideobuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysignalhandler.o mysignalhandler.cpp

cliente.o: cliente.cpp cliente.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QObject \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qflags.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstring.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qchar.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/QTcpSocket \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qhash.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpair.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvector.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qset.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QCamera \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamera.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsize.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrect.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediacontrol.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmultimedia.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaservice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraexposure.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmediaenumdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetaobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcamerafocus.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qcameraimageprocessing.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QMovie \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmovie.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimagereader.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qregion.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qline.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimageiohandler.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qplugin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qjsonvalue.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfactoryinterface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTimer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasictimer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QTime \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatetime.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPixmap \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qcolor.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QBuffer \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QPainter \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainter.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtextoption.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpen.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qbrush.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfont.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qfontmetrics.h \
		cvmatandqimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QImage \
		capturebuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QDebug \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QAbstractVideoSurface \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideosurface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qvideoframe.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideobuffer.h \
		protocol.pb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QSettings \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cliente.o cliente.cpp

capturebuffer.o: capturebuffer.cpp capturebuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QDebug \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qflags.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qhash.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qchar.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpair.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstring.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvector.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qset.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/QAbstractVideoSurface \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideosurface.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qvideoframe.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrect.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsize.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qregion.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qline.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qabstractvideobuffer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qtmultimediadefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtMultimedia/qmultimedia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capturebuffer.o capturebuffer.cpp

cvmatandqimage.o: cvmatandqimage.cpp cvmatandqimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/QImage \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qimage.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvector.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qflags.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qrect.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qsize.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qregion.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstring.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qchar.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qpair.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qline.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QSysInfo \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/QDebug \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qhash.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qmap.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qset.h \
		../Qt5.2.0/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvmatandqimage.o cvmatandqimage.cpp

protocol.pb.o: protocol.pb.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o protocol.pb.o protocol.pb.cc

moc_mysignalhandler.o: moc_mysignalhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mysignalhandler.o moc_mysignalhandler.cpp

moc_cliente.o: moc_cliente.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cliente.o moc_cliente.cpp

moc_capturebuffer.o: moc_capturebuffer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_capturebuffer.o moc_capturebuffer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

